//api's
export const SET_MY_FAVOTITES = 'SET_MY_FAVOTITES';
export const SET_DAILT_FORCECASTS = 'SET_DAILT_FORCECASTS';
export const SET_CURRENT_CONDITIONS = 'SET_CURRENT_CONDITIONS';
export const SET_AUTOCOMPLETE_SEARCH = 'SET_AUTOCOMPLETE_SEARCH';

//routes
export const SET_APPLICATION_PAGE = 'SET_APPLICATION_PAGE';


