export const answerTypes = {
    INPUT: 'Input',
    LABEL: 'Label',
};

export const questionTopics = {
    PATIENT_CHARACTERISTICS: 'Patient Characteristics',
    TREATMENT: 'Treatment'
};

export const navbarTags = {
    PATIENT_ID: 'Patient ID',
    BREAST_SIZE: 'Breast Size',
    PATIENT_WEIGHT: 'Patient Weight',
    PATIENT_HEIGHT: 'Patient Height',
    PATIENT_AGE: 'Patient Age',
    MENOPAUSAL_STATUS: 'Menopausal Status',
    PROGESTERONE_RECEPTOR: 'Progesterone Receptor',
    PV_V107: 'PV-V107%',
    TV_110: 'TV-V110%',
    IMRT_VS_STANDART_WEDGE_RT: 'IMRT vs standard wedge RT',
    TAMOXIFEN: 'Tamoxifen',
    CF_VS_HS: 'CF vs HS',
    AXILA: 'Axila',
    COBALT_VS_LINEAR: 'Cobalt vs Linear',
    DOSE: 'Dose'
};

export const questions = {
    PATIENT_ID: 'Patient ID number',
    BREAST_SIZE: 'What is the size of the patient’s breast?',
    PATIENT_WEIGHT: 'What is the patient’s weight (Kg)?',
    PATIENT_HEIGHT: 'What is the patient’s height (Cm)?',
    PATIENT_AGE: 'What is the age of the patient?',
    MENOPAUSAL_STATUS: 'What is the patient’s menapausal status?',
    PROGESTERONE_RECEPTOR: 'Progesterone receptor',
    PV_V107: 'PV-V107% (cc)',
    TV_110: 'TV-V110% (%)',
    IMRT_VS_STANDART_WEDGE_RT: 'IMRT vs standard wedge RT',
    TAMOXIFEN: 'Tamoxifen',
    CF_VS_HS: 'Fractionation schedule (CF) vs moderate hypofractionated (HS)',
    AXILA: 'Axila included in field of rediation',
    COBALT_VS_LINEAR: 'Cobalt-60 vs Linear Accelerator',
    DOSE: 'Dose'
};

export const possibleAnswers = {
    D: 'D',
    C: 'C',
    AB: 'AB',
    POST: 'Post',
    PRE: 'Pre',
    POSITIVE: 'Positive',
    NEGATIVE: 'Negative',
    IMRT: 'IMRT',
    CONVENTIONAL: 'Conventional',
    YES: 'Yes',
    NO: 'No',
    CF: 'CF',
    HS: 'HS',
    COBALT_60: 'Cobalt-60',
    LINEAR_ACCELERATOR: 'Linear accelerator',
    DOSE_A: '>50 gray',
    DOSE_B: '<50 gray'
};

export const reduxAnswersName = {
    ID_NUMBER: 'idNumber',
    BREAST_SIZE: 'breastSize',
    WEIGHT: 'weight',
    HEIGHT: 'height',
    AGE: 'age',
    MENOPAUSAL_STATUS: 'menopausalStatus',
    PROGESTERONE_RECEPTOR: 'progesteroneReceptor',
    PV: 'pv',
    TV: 'tv',
    IMRT: 'imrt',
    TAMOXIFEN: 'tamoxifen',
    CF_HS: 'cfHs',
    AXILA: 'axila',
    COBALT_VS_LINEAR: 'cobaltVsLinear',
    DOSE: 'dose',
};
// @ts-ignore
export interface Question {
    id: number,
    topicName: string,
    tagName: string,
    question: string,
    answers: string[],
    answerType: string,
    reduxAnswerName: Property,
    lineBottom: boolean,
}

type Property = 'idNumber' | 'breastSize' | 'weight' | 'height' | 'age' | 'menopausalStatus' | 'progesteroneReceptor' | 'pv' | 'tv' | 'imrt' | 'tamoxifen' | 'cfHs' | 'axila' | 'cobaltVsLinear' | 'dose';

export const arrayQuestions: Question[] = [
    {
        id: 0,
        topicName: questionTopics.PATIENT_CHARACTERISTICS,
        tagName: navbarTags.PATIENT_ID,
        question: questions.PATIENT_ID,
        answers: null,
        answerType: answerTypes.INPUT,
        reduxAnswerName: 'idNumber',
        lineBottom: true,
    },
    {
        id: 1,
        topicName: questionTopics.PATIENT_CHARACTERISTICS,
        tagName: navbarTags.BREAST_SIZE,
        question: questions.BREAST_SIZE,
        answers: [possibleAnswers.D, possibleAnswers.C, possibleAnswers.AB],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'breastSize',
        lineBottom: false,
    },
    {
        id: 2,
        topicName: questionTopics.PATIENT_CHARACTERISTICS,
        tagName: navbarTags.PATIENT_WEIGHT,
        question: questions.PATIENT_WEIGHT,
        answers: null,
        answerType: answerTypes.INPUT,
        reduxAnswerName: 'weight',
        lineBottom: true,
    },
    {
        id: 3,
        topicName: questionTopics.PATIENT_CHARACTERISTICS,
        tagName: navbarTags.PATIENT_HEIGHT,
        question: questions.PATIENT_HEIGHT,
        answers: null,
        answerType: answerTypes.INPUT,
        reduxAnswerName: 'height',
        lineBottom: false,
    },
    {
        id: 4,
        topicName: questionTopics.PATIENT_CHARACTERISTICS,
        tagName: navbarTags.PATIENT_AGE,
        question: questions.PATIENT_AGE,
        answers: null,
        answerType: answerTypes.INPUT,
        reduxAnswerName: 'age',
        lineBottom: true,
    },
    {
        id: 5,
        topicName: questionTopics.PATIENT_CHARACTERISTICS,
        tagName: navbarTags.MENOPAUSAL_STATUS,
        question: questions.MENOPAUSAL_STATUS,
        answers: [possibleAnswers.POST, possibleAnswers.PRE],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'menopausalStatus',
        lineBottom: true,
    },
    {
        id: 6,
        topicName: questionTopics.PATIENT_CHARACTERISTICS,
        tagName: navbarTags.PROGESTERONE_RECEPTOR,
        question: questions.PROGESTERONE_RECEPTOR,
        answers: [possibleAnswers.POSITIVE, possibleAnswers.NEGATIVE],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'progesteroneReceptor',
        lineBottom: true,
    },
    {
        id: 7,
        topicName: questionTopics.TREATMENT,
        tagName: navbarTags.PV_V107,
        question: questions.PV_V107,
        answers: null,
        answerType: answerTypes.INPUT,
        reduxAnswerName: 'pv',
        lineBottom: true,
    },
    {
        id: 8,
        topicName: questionTopics.TREATMENT,
        tagName: navbarTags.TV_110,
        question: questions.TV_110,
        answers: null,
        answerType: answerTypes.INPUT,
        reduxAnswerName: 'tv',
        lineBottom: true,
    },
    {
        id: 9,
        topicName: questionTopics.TREATMENT,
        tagName: navbarTags.IMRT_VS_STANDART_WEDGE_RT,
        question: questions.IMRT_VS_STANDART_WEDGE_RT,
        answers: [possibleAnswers.IMRT, possibleAnswers.CONVENTIONAL],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'imrt',
        lineBottom: true,
    },

    {
        id: 10,
        topicName: questionTopics.TREATMENT,
        tagName: navbarTags.TAMOXIFEN,
        question: questions.TAMOXIFEN,
        answers: [possibleAnswers.YES, possibleAnswers.NO],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'tamoxifen',
        lineBottom: true,
    },
    {
        id: 11,
        topicName: questionTopics.TREATMENT,
        tagName: navbarTags.CF_VS_HS,
        question: questions.CF_VS_HS,
        answers: [possibleAnswers.CF, possibleAnswers.HS],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'cfHs',
        lineBottom: true,
    },
    {
        id: 12,
        topicName: questionTopics.TREATMENT,
        tagName: navbarTags.AXILA,
        question: questions.AXILA,
        answers: [possibleAnswers.YES, possibleAnswers.NO],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'axila',
        lineBottom: true,
    },
    {
        id: 13,
        topicName: questionTopics.TREATMENT,
        tagName: navbarTags.COBALT_VS_LINEAR,
        question: questions.COBALT_VS_LINEAR,
        answers: [possibleAnswers.COBALT_60, possibleAnswers.LINEAR_ACCELERATOR],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'cobaltVsLinear',
        lineBottom: true,
    },
    {
        id: 14,
        topicName: questionTopics.TREATMENT,
        tagName: navbarTags.DOSE,
        question: questions.DOSE,
        answers: [possibleAnswers.DOSE_A, possibleAnswers.DOSE_B],
        answerType: answerTypes.LABEL,
        reduxAnswerName: 'dose',
        lineBottom: false,
    },
];